config/routes.rb
Rails.application.routes.draw do
  resources :animals
  resources :forests
  resources :visitors
  root to: 'forests#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord
  has_many :forests
  has_many :visitors, through: :forests

  def animal_stuff
    "#{self.name} | #{self.species}"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/forest.rb
class Forest < ApplicationRecord
  belongs_to :visitor
  belongs_to :animal

  def forest_name
    "#{self.forest}"
  end

end

app/models/visitor.rb
class Visitor < ApplicationRecord
  has_many :forests
  has_many :animals, through: :forests
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController

  def index
    @animals = Animal.all
  end

  def show
    @animal = Animal.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/forests_controller.rb
class ForestsController < ApplicationController

  def index
    @forests = Forest.all
  end

  def new
    @forest = Forest.new
  end

  def create
    # forestArr = [
    #   "Hoh Rainforest",
    #   "Yellowstone National Park",
    #   "Hickory Run State Park",
    #   "Lake Minnewaska",
    #   "Indiana Dunes",
    #   "The Black Forest",
    #   "Sherwood Forest",
    #   "Giant Redwoods Forest",
    #   "Tongass National Forest",
    #   "The Inland Rainforest",
    #   "The Great Bear Rainforest",
    #   "The Cloud Forests",
    #   "Laputa",
    #   "El Yunque",
    #   "Nouabalé-Ndoki National Park"
    # ]
    # @forest = Forest.create(visitor_id: Visitor.all.sample.id, animal_id: Animal.all.sample.id, forest: forestArr.sample)
    @forest = Forest.create(check_params)
    if @forest.save
      redirect_to forests_path
    else
      render "new"
    end
  end

private

  def check_params
    params.require(:forest).permit(:visitor_id, :animal_id, :forest)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def index
    @visitors = Visitor.all
  end

  def new
    @visitor = Visitor.new
  end

  def create
    @visitor = Visitor.create(require_params)
    if @visitor.save
      redirect_to visitors_path(@visitor)
    else
      render "new"
    end
  end

  def show
    @visitor = Visitor.find(params[:id])
  end

  def edit
    @visitor = Visitor.find(params[:id])
  end

  def update
    @visitor = Visitor.find(params[:id])
    @visitor.update(require_params)
    redirect_to visitor_path(@visitor)
  end

  def destroy
    @visitor = Visitor.find(params[:id])
    @visitor.destroy
    redirect_to visitors_path
  end

private

def require_params
  params.require(:visitor).permit(:name)
end

end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forests_helper.rb
module ForestsHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/animals/index.html.erb
<h1>Animals Index</h1>
<%@animals.each do|animal| %>
<%= link_to animal.name, animal %> the
<%= animal.species %>
<br>
<%end %>
<br>
  <%= button_to "New Forest Visit", new_forest_path(@forest), method: :get%>

app/views/animals/show.html.erb
<h1><%=@animal.name%> the <%=@animal.species%>'s Friends</h1>

  <% @animal.visitors.each do |visitor| %>
  <ul><%= visitor.name %></ul>
  <% end %>

  <%= button_to "New Forest Visit", new_forest_path(@forest), method: :get%>
  <%= button_to "Back to Animals Index", animals_path, method: :get%>

app/views/forests/index.html.erb
<h1>Meditation Visits in Forests</h1>

  <% @forests.each do |f| %>
  <ul><%=  f.visitor.name %> meditates with
  <%= f.animal.name%> who is a
  <%= f.animal.species %>
  in <%= f.forest_name %><br></ul>
  <% end %>
<br>
<%= button_to "New Forest Visit", new_forest_path, method: :get %>
<%= button_to "Visitors Index", visitors_path, method: :get%>
<%= button_to "Animals Index", animals_path, method: :get%>

app/views/forests/new.html.erb
<h1>Create a Forest Visit</h1>

<%= form_for @forest do |t| %>
<%= t.label :visitor_id%>
<%= t.collection_select :visitor_id, Visitor.all, :id, :name %>
<%= t.label :animal_id%>
<%= t.collection_select :animal_id, Animal.all, :id, :animal_stuff %>
<%= t.text_field :forest, :placeholder => 'Create a new forest!'%>
<%= t.submit text="Create New Visit"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeditationApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/visitors/edit.html.erb
<h1><%= @visitor.name %>'s Page</h1>

     <%= form_for @visitor do |f| %>
      name:<%= f.text_field :name %>
      <%= f.submit %>
    <% end %>
<br>
  <%= button_to "Delete Visitor", visitor_path, method: :delete %>
  <%= button_to "Back to Visitors Index", visitors_path, method: :get%>

app/views/visitors/index.html.erb
<h1>Visitors Page</h1>

<% @visitors.each do |visitor| %>
<%= link_to visitor.name, visitor %>
<br>
<% end %>
<br>
<%= button_to "New Visitor", new_visitor_path(@visitor), method: :get%>
<%= button_to "New Forest Visit", new_forest_path, method: :get %>

app/views/visitors/new.html.erb
<h1>Create a new Visitor</h1>

 <%= form_for @visitor do |f| %>
  name:<%= f.text_field :name %>
  <%= f.submit %>
<% end %>
<br>
<%= button_to "Back to Visitor Index", visitors_path, method: :get %>

app/views/visitors/show.html.erb
<h1><%= @visitor.name %>'s Friends</h1>

    <% @visitor.animals.each do |animal| %>
    <ul><%= animal.name  %> the
    <%= animal.species  %></ul>
    <% end %>
<%= button_to "Edit Visitor Name", edit_visitor_path,method: :get %>
<%= button_to "Visitors Index", visitors_path, method: :get%>